### ISSUE TITLE
Checking new version

### ISSUE THREAD

**Issue by Mefuuu** [ShaneBeee/RandomTP#1]
On script load:
```
[RandomTP] - Running version: 1.2.0
[RandomTP] - Update available, version: <none>
```
http request doesn't work?

**Comment by ShaneBeee** [comment]
Works fine for me:
```
[11:50:56 INFO]: [Skript] Finished loading.
[11:50:56 INFO]: [RTP] - Loaded successfully
[11:50:56 INFO]: [RandomTP] - Running current version: 1.2.0
```

Do you have all the correct Skript addons installed?

**Comment by Mefuuu** [comment]
Yes, https://gyazo.com/b38db82ee1b9bef02f35d81d3c5c44b1 (screen shot)
mc version is 1.14.4

**Comment by ShaneBeee** [comment]
Im not sure then. I ran it thru my test server and it seemed totally fine. 

I recommend just ignoring it, its not really a big deal if it says that.

**Comment by Mefuuu** [comment]
Maybe it doesn't bother me in rtp, but I'm also doing a script and I wanted to get this "http request" to my script, it doesn't work  :C

**Comment by ShaneBeee** [comment]
> Maybe it doesn't bother me in rtp, but I'm also doing a script and I wanted to get this "http request" to my script, it doesn't work :C

Maybe its an issue with your computer or Skript, I have no clue, you'd have to reach out to the dev of Reqn
